

const PRODUCTS = [
  {
    id: "merid-40-steel",
    name: "Meridian 40",
    category: "Sports",
    movement: "Quartz",
    case: "Stainless Steel, 40mm",
    strap: "Steel bracelet",
    price: 18500,
    compareAt: 26500,
    tag: "Bestseller",
    collection: "Sports",
    seed: "images/7e77b281-ad8d-4352-8684-832f4783d85e.png",
    gallery: ["images/7e77b281-ad8d-4352-8684-832f4783d85e.png", "images/96f41e45-42c6-4edc-98fd-325fa1e1014c.png", "images/128aeeda-e813-4c6f-89cb-01a14f226db4.png"],
    blurb: "A clean three-hand dial built for every day. Brushed case, sapphire-coated crystal, 5ATM water resistance."
  },
  {
    id: "solace-leather",
    name: "Solace",
    category: "Luxury",
    movement: "Quartz",
    case: "Stainless Steel, 42mm",
    strap: "Full-grain leather",
    price: 15900,
    compareAt: 21000,
    tag: "New",
    collection: "luxury",
    seed: "images/7c25481a0e774a88a201ed2aab9dad27-goods.png",
    gallery: ["images/7c25481a0e774a88a201ed2aab9dad27-goods.png", "images/8af153c24a594585bc5541598a2689d1-goods.png", "images/87bd56b5b6fc42e9b0dfad678ae92ed7-goods.png"],
    blurb: "Warm tan leather against a matte black dial — a watch that goes from the office to a Friday out."
  },
  {
    id: "aster-bracelet",
    name: "Aster",
    category: "Luxury",
    movement: "Quartz",
    case: "Stainless Steel, 32mm",
    strap: "Mesh bracelet",
    price: 13400,
    compareAt: 17900,
    tag: "Bestseller",
    collection: "luxury",
    seed: "images/watch1.png",
    gallery: ["images/watch1.png", "images/watch1.2.png", "images/watch1.3.png"],
    blurb: "A slim mesh bracelet and a sunburst dial that catches light without trying too hard."
  },
  {
    id: "veil-pearl",
    name: "Veil",
    category: "Luxury",
    movement: "Quartz",
    case: "Stainless Steel, 30mm",
    strap: "Two-tone bracelet",
    price: 16200,
    compareAt: 22800,
    tag: "Limited",
    collection: "luxury",
    seed: "images/POEDAGAR1.png",
    gallery: ["images/POEDAGAR1.png", "images/POEDAGAR2.png", "images/POEDAGAR3.png"],
    blurb: "Mother-of-pearl dial, rose-gold accents. Small enough for a slim wrist, sturdy enough for every day."
  },
  {
    id: "harbor-chrono",
    name: "Aero Chronograph",
    category: "sports",
    movement: "Quartz Chronograph",
    case: "Stainless Steel, 44mm",
    strap: "Silicone",
    price: 19800,
    compareAt: 27500,
    tag: null,
    collection: "sports",
    seed: "images/aero-chronograph-3.png",
    gallery: ["images/aero-chronograph-3.png", "images/aero-chronograph-2.png", "images/aero-chronograph-1.png"],
    blurb: "A bold chronograph with three sub-dials, a tachymeter bezel, and a durable silicone strap built for fast-paced days."
  },
  {
    id: "linden-gold",
    name: "Linden",
    category: "Luxury",
    movement: "Quartz",
    case: "Gold-tone Steel, 34mm",
    strap: "Steel bracelet",
    price: 17600,
    compareAt: 23900,
    tag: "Bestseller",
    collection: "luxury",
    seed: "images/hikun1.png",
    gallery: ["images/hikun1.png", "images/hikun2.png", "images/hikun3.png"],
    blurb: "A gold-toned case with a champagne dial — the one watch that matches everything in your closet."
  },
  {
    id: "field-utility",
    name: "Trail Pro",
    category: "sports",
    movement: "Quartz",
    case: "Matte Steel, 41mm",
    strap: "Canvas NATO",
    price: 12900,
    compareAt: 16500,
    tag: null,
    collection: "sports",
    seed: "images/trail-pro-1.png",
    gallery: ["images/trail-pro-1.png", "images/trail-pro-2.png", "images/trail-pro-3.png"],
    blurb: "A rugged field watch with a matte case, luminous markers, and a weather-ready canvas strap for outdoor adventures."
  },
  {
    id: "sport-01",
    name: "Endurance One",
    category: "sports",
    collection: "sports",
    movement: "Quartz",
    case: "Sport steel, 42mm",
    strap: "Performance strap",
    price: 14900,
    compareAt: 18900,
    tag: "New",
    seed: "images/ENKY_Watch_1_4K.png",
    gallery: ["images/ENKY_Watch_1_4K.png"],
    blurb: "A clean, durable sports watch with a comfortable performance strap for training, travel, and everyday movement."
  },
  {
    id: "sport-02",
    name: "Pace One",
    category: "sports",
    collection: "sports",
    movement: "Quartz",
    case: "Sport steel, 44mm",
    strap: "Silicone",
    price: 15900,
    compareAt: 19900,
    tag: null,
    seed: "images/ENKY_Watch_2_4K.png",
    gallery: ["images/ENKY_Watch_2_4K.png"],
    blurb: "A bold everyday sports watch with a strong dial layout, lightweight feel, and easy-read markers."
  },
  {
    id: "sport-03",
    name: "Motion One",
    category: "sports",
    collection: "sports",
    movement: "Quartz Chronograph",
    case: "Stainless Steel, 44mm",
    strap: "Silicone",
    price: 17900,
    compareAt: 22900,
    tag: "Bestseller",
    seed: "images/ENKY_Watch_3_4K.png",
    gallery: ["images/ENKY_Watch_3_4K.png"],
    blurb: "A confident chronograph-inspired sports watch designed for active days and a sharp finish after training."
  },
  {
    id: "sport-04",
    name: "Summit One",
    category: "sports",
    collection: "sports",
    movement: "Quartz",
    case: "Matte steel, 41mm",
    strap: "Textile strap",
    price: 13900,
    compareAt: 17500,
    tag: null,
    seed: "images/ENKY_Watch_4_4K.png",
    gallery: ["images/ENKY_Watch_4_4K.png"],
    blurb: "A versatile field-sport watch with a practical case, clear markers, and a strap ready for the outdoors."
  },
  {
    id: "sport-05",
    name: "Apex One",
    category: "sports",
    collection: "sports",
    movement: "Quartz",
    case: "Sport steel, 43mm",
    strap: "Rubber strap",
    price: 16900,
    compareAt: 21500,
    tag: "New",
    seed: "images/ENKY_Watch_5_4K.png",
    gallery: ["images/ENKY_Watch_5_4K.png"],
    blurb: "A modern sports watch with a high-contrast face and secure rubber strap for reliable all-day comfort."
  },
  {
    id: "sport-06",
    name: "Circuit One",
    category: "sports",
    collection: "sports",
    movement: "Quartz Chronograph",
    case: "Stainless Steel, 45mm",
    strap: "Silicone",
    price: 18900,
    compareAt: 23900,
    tag: null,
    seed: "images/ENKY_Watch_6_4K.png",
    gallery: ["images/ENKY_Watch_6_4K.png"],
    blurb: "A statement sports chronograph with a technical dial and flexible strap built for fast-paced routines."
  },
  {
    id: "luxury-01",
    name: "Celestial Tourbillon",
    category: "luxury",
    collection: "luxury",
    movement: "Automatic",
    case: "Rose-gold steel, 42mm",
    strap: "Black leather",
    price: 42500,
    compareAt: 52000,
    tag: "New",
    seed: "images/ENKY_New_Watch_1_4K.png",
    gallery: ["images/ENKY_New_Watch_1_4K.png"],
    blurb: "A dramatic rose-gold timepiece with a deep blue skeleton dial, celestial detailing, and a refined black leather strap."
  },
  {
    id: "luxury-02",
    name: "Regent Chronograph",
    category: "luxury",
    collection: "luxury",
    movement: "Quartz Chronograph",
    case: "Gold-tone steel, 44mm",
    strap: "Black leather",
    price: 38900,
    compareAt: 47500,
    tag: "Limited",
    seed: "images/ENKY_New_Watch_2_4K.png",
    gallery: ["images/ENKY_New_Watch_2_4K.png"],
    blurb: "A bold navy chronograph framed in polished gold tones, pairing confident sub-dials with a classic leather strap."
  },
  {
    id: "luxury-03",
    name: "Nocturne Chronograph",
    category: "luxury",
    collection: "luxury",
    movement: "Automatic Chronograph",
    case: "Rose-gold steel, 43mm",
    strap: "Black rubber",
    price: 39900,
    compareAt: 49000,
    tag: null,
    seed: "images/ENKY_New_Watch_3_4K.png",
    gallery: ["images/ENKY_New_Watch_3_4K.png"],
    blurb: "A black-and-rose-gold chronograph with luminous markers and a performance-ready strap beneath its luxury finish."
  },
  {
    id: "luxury-04",
    name: "Emerald Grand",
    category: "luxury",
    collection: "luxury",
    movement: "Automatic Chronograph",
    case: "Gold-tone steel, 44mm",
    strap: "Gold-tone bracelet",
    price: 44900,
    compareAt: 56500,
    tag: "Bestseller",
    seed: "images/ENKY_New_Watch_4_4K.png",
    gallery: ["images/ENKY_New_Watch_4_4K.png"],
    blurb: "An emerald-green dial and sculpted gold-tone bracelet give this statement chronograph a rich, unmistakable presence."
  },
  {
    id: "luxury-05",
    name: "Obsidian Regent",
    category: "luxury",
    collection: "luxury",
    movement: "Automatic",
    case: "Black and rose-gold steel, 43mm",
    strap: "Black leather",
    price: 41900,
    compareAt: 52500,
    tag: "New",
    seed: "images/ENKY_New_Watch_5_4K.png",
    gallery: ["images/ENKY_New_Watch_5_4K.png"],
    blurb: "A sculpted black dial, rose-gold accents, and a textured leather strap create a dark, elegant statement for evening wear."
  },
  {
    id: "hammer-chrono-60",
    name: "Hammer 6.0",
    category: "Sports",
    movement: "Quartz Analog-Digital",
    case: "Rose-gold Steel, 44mm",
    strap: "Full-grain leather",
    price: 22900,
    compareAt: 29900,
    tag: "New",
    collection: "sports",
    seed: "images/watch.png",
    gallery: ["images/watch.png"],
    blurb: "A rugged analog-digital hybrid with a rose-gold case, dual displays, and a hand-stitched leather strap built for every day."
  },
  {
    id: "delex-clover",
    name: "Delex Clover",
    category: "Luxury",
    movement: "Quartz",
    case: "Stainless Steel, 26mm",
    strap: "Diamond-set bracelet",
    price: 34900,
    compareAt: 45900,
    tag: "Limited",
    collection: "luxury",
    seed: "images/watch-1.png",
    gallery: ["images/watch-1.png"],
    blurb: "A clover-shaped mother-of-pearl dial framed in pavé crystal, set on a matching clover-link bracelet."
  },
  {
    id: "noir-minimal",
    name: "Noir Minimal",
    category: "Luxury",
    movement: "Quartz",
    case: "Stainless Steel, 40mm",
    strap: "Steel bracelet",
    price: 19900,
    compareAt: 25900,
    tag: "Bestseller",
    collection: "luxury",
    seed: "images/watch-2.png",
    gallery: ["images/watch-2.png"],
    blurb: "A minimalist black sunray dial on a brushed steel bracelet, built for a clean, everyday-formal look."
  },
  {
    id: "sveston-chrono-navy",
    name: "Sveston Chronograph 2.0",
    category: "Luxury",
    movement: "Quartz Chronograph",
    case: "Stainless Steel, 42mm",
    strap: "Tan leather",
    price: 20900,
    compareAt: 26900,
    tag: null,
    collection: "sports",
    seed: "images/watch-3.png",
    gallery: ["images/watch-3.png"],
    blurb: "A navy tri-compax dial with day, date, and 24-hour sub-dials, paired with a warm tan leather strap."
  },
  {
    id: "aspire-classic",
    name: "Aspire Classic",
    category: "Luxury",
    movement: "Quartz",
    case: "Stainless Steel, 40mm",
    strap: "Leather",
    price: 17900,
    compareAt: 22900,
    tag: null,
    collection: "luxury",
    seed: "images/watch-4.png",
    gallery: ["images/watch-4.png"],
    blurb: "A clean silver dial with a date window on a brown leather strap — a dependable classic for daily wear."
  }
];


function formatPKR(n) {
  return "Rs. " + n.toLocaleString("en-PK");
}

function getProductById(id) {
  return PRODUCTS.find(function (p) { return p.id === id; });
}
